//
//  GlobalData.swift
//  Faithbuilders
//
//  Created by Curtis Wilson on 6/14/16.
//  Copyright © 2016 Eusebeia. All rights reserved.
//

import UIKit
class GlobalData
{
    // Singleton Setup
    
    fileprivate static var info: GlobalData?
    let speakers: Array<Speaker>
    let classes: Array<Class>
    
    class func getInstance() -> GlobalData
    {
        if self.info == nil
        {
            self.info = GlobalData()
        }
        
        return self.info!
    }
    
    func findSpeakerByName(_ name: String) -> Speaker? {
        var i: Int = 0
        while (i < speakers.count) {
            if (speakers[i].name == name) {
                return speakers[i]
            }
            i += 1
        }
        return nil
    }
    
    // Class properties
    init() {
        speakers = [
            Speaker(name:"Behailu Endeshaw", location:"Kent, WA", photo:UIImage(named:"behailuendeshaw")!, description:"I have served as a full-time minister with the Churches of Christ for over 55 years in Ethiopia, Nairobi, Kenya and currently in USA.\n\nServed as the Church of Christ Mission Director, Addis Ababa, Ethiopia. (1974 to 2016).\n\nServed as the Dean of Five Preacher Training Schools (SIBI Branch Schools) in Ethiopia. (1974-2016), Helped train more than 2,000 preachers.\n\nLed a campaign to establish up to 1200 congregations.\n\nAdministrated 5 Schools for the Deaf, 3 Kindergartens for destitute children.\n\nLed and Organized the largest Church of Christ Emergency Famine Project and Distributed Lifesaving Food to over 128,000 starving people.\n\nConsolidated Water Well Development Project in Ethiopia. Drilled over 650 boreholes that provide clean water to 2.5 million people.\n\nTranslated (print and audio form) the 40 Biblical Courses of SIBI into Amharic, the national language of Ethiopia. This may well be the greatest single need for the development of the rapidly growing churches of Christ in Ethiopia.\n\nMINISTRY ACCOLADES:\n\nHonorary Doctorate recipient (Harding University 1996)\n\nHonorary Doctorate recipient (Abilene Christian University 1996)\n\nHonorary Doctorate recipient (American Christian Bible College 1996)\n\nChristian Service Award (Pepperdine University 2001)\n\nWorld Changer Award (Sunset International Bible Institute 2015)\n\nTo His Glory\n\nBehailu A. Endeshaw"),
            Speaker(name:"Carrell Dennis", location:"Renton, WA", photo:UIImage(named:"carrelldennis")!, description: "Carrell Dennis earned a Bachelor of Science Degree from Eastern New Mexico University before attending the Sunset School of Preaching, where he earned a diploma in Bible and Missions. In 1982, he planted the Covington Sawyer church of Christ, Covington Washington and helped establish the Lord's church in Bratislava, Slovakia. He is currently one of the Elders at the Springbrook church of Christ in Renton, Washington."),
            Speaker(name:"Jack Keller", location:"Ferndale, WA", photo:UIImage(named:"jackkeller")!, description:"Jack Keller has been a minister and family counselor for almost 45 years. He earned a Ph.D. degree from Cornerstone University in Clinical Christian Counseling. He is a Licensed Clinical Pastoral Counselor with the National Christian Counselors Association. Jack is a graduate of Sunset International Bible Institute in Lubbock, Texas, (formerly SSOP.) He and his wife, Linda, along with two other families helped establish the congregation of the Lord's church in Ferndale, Washington in 1967. He has served congregations in Washington and California. He has spoken on workshops, seminars, and held meetings in Canada, Washington, Oregon and California. He has written a commentary on the Corinthian letters and many study guides on a number of Bible topics and books of the New Testament. He is back at the church in Ferndale serving for the second time as its pulpit minister. He is in his thirty fourth consecutive year as a minister for the congregation. Jack also directs the Portal Way Bible Institute. He teaches counseling and Bible courses at the institute. He and his wife Linda have been married for over fifty one years and have two daughters and four grandchildren."),
            Speaker(name:"Jody Apple", location:"Knoxville, TN", photo:UIImage(named:"jodyapple")!, description:"Jody L Apple is in his 30th year of preaching & teaching for the Lord's church. He completed 23 years with the church in Media, PA (suburban Philadelphia) in December 2006 and now works full-time with TheBible.net and its online schools: Internet School of Biblical Studies, Video Bible Institute and SchoolOfBiblicalStudies.org.\n\nHe is a graduate of Freed-Hardeman University and the Graduate School of Tennessee Bible College. He has pursued additional graduate work in philosophy and religious studies at Harding Graduate School of Religion, Southern Christian University, Westminster Theological Seminary and West Chester University.\n\nJody is the author of Hermeneutical Agnosticism: A Critique of Subjectivism in Biblical Interpretation, as well as numerous articles in brotherhood journals and lectureship books.\n\nHe is the originator and administrator of TheBible.net, an online site devoted to evangelism and edification - TheBible.net hosts ISBS & VBI. He also serves as an instructor and assists in directing the school.\n\nJody and his wife, Evelyn, have three children - Jonathan, Benjamin and Julia. He is a persistent jogger, loves Macs (the computers not the hamburgers), and is an avid reader."),
            Speaker(name:"Kevin Bethea", location:"Baltimore, MD", photo:UIImage(named:"kevinbethea")!, description:"Brother Kevin Bethea is the Senior Minister of the East Baltimore church of Christ in Baltimore, Maryland. He also currently serves as president of the Northeast Baltimore Bible Institute & College. Brother Bethea was born in Baltimore, Maryland. He is a former second generation Pentecostal preacher, as he was converted into the Lord's church in the late 1980s. Brother Bethea was retrained by the school of external studies, SIBI, and holds an M.A. degree in Clinical Counseling from the Cornerstone University. Brother Bethea also received an honorary Masters degree in Biblical Studies from the University of Bible in Baltimore. He became the assistant minister at the Metropolitan church of Christ in 1992. During this time, he was regarded for his strong Biblical teachings and evangelistic abilities. With a vision to plant a new work in Baltimore, he has served at the East Baltimore church of Christ since December 1995, and helped to form a healthy and happy congregation of more than 375 members. Brother Bethea also serves as a Certified Sunset International Bible Institute Satellite School Administrator.\n\nBrother Bethea has preached Gospel Meetings and held workshops in Georgia, New York, Pennsylvania, Texas, North Carolina, Virginia and the DC areas. He was a speaker in the Mid-Atlantic, Southeast & Nations Capital Lectureships and Mid-Atlantic marriage retreat and seminar hosted by the Prince Georges church of Christ.  For a total of 9 years, Kevin hosted a live, call-in radio program entitled \"Search the Scriptures\", which was instrumental in increasing the kingdom of God in the Baltimore metropolitan area.  This live, call-in radio program paved the way for others to begin to challenge the charismatic movement and return back to the Lord's church."),
            Speaker(name:"Lori Boyd", location:"Murfreesboro, TN", photo:UIImage(named:"loriboyd")!, description:"Lori Boyd is from Murfreesboro, Tennessee and attends the East Main Church of Christ. She and her husband, Sam, have been married for seventeen years and have three children, Evie (14), Kate (12), and Briggs (9). Lori is a Registered Nurse and works as a Nursing Supervisor at St. Thomas Rutherford Hospital in Murfreesboro. She is also currently enrolled in classes at the Nashville School of Preaching and Biblical Studies.\n\nLori has written for Think magazine and has developed several Bible studies for women. Her first published book, Trailblazers, was released at the end of last year and she is currently working on the completion of her second book, entitled Walking to the Promised Land. She has a passion for public speaking and enjoys presenting regularly at ladies’ events and retreats.\n\nLori was born in Germany and had the wonderful opportunity to live all across the United States while growing up in the Air Force. She attended Abilene Christian University in Texas and graduated from the Abilene Intercollegiate School of Nursing in 1996. She moved to Nashville in June of 1997 and has called Middle Tennessee “home” ever since. Some of her favorite things include spending time with her family, writing, reading, speaking, teaching, and traveling. Above everything else, she loves the Lord, His church, and the incredible joy that comes with being a Christian."),
            Speaker(name:"Mark Jamieson", location:"Puyallup, WA", photo:UIImage(named:"markjamieson")!, description: "Mark Jamieson is currently serving as the pulpit minister for the Puyallup Church of Christ which meets in Puyallup, Washington. He previously served the Lord's church in Gulf Shores, Alabama; Columbia, Tennessee; and Franklin, Kentucky as their pulpit minister.  He currently works as an adjunct instructor with the Guyana Christian University in Lethem, Guyana (South America). He is a former instructor with the Nashville School of Preaching and Biblical Studies, Philippine Theological College, and the Columbia (Tennessee) School of Preaching and Biblical Studies. He is the son of LtCol Leo R. Jamieson of Montgomery, Alabama, and Peggie Derryberry Jamieson of Pulaski, Tennessee. He was reared in the United States Marine Corps from Long Island, New York, to Mission Viejo, California, and attended 10 different schools Kindergarten through high school graduation. He has one brother, Lee, of Tallahassee, Florida, who is also a gospel preacher.\n\nHe is married to the former Suzy Yeomans, of Shelby, North Carolina, his wife of over 30 years.  Together they have two sons, Kevin, 29, and David, 27. He holds a BA in Biblical Studies from Southern Christian University and an MA in Biblical Studies from Amridge University, formerly Southern Christian University, and has done post-graduate studies at Amridge University towards a PhD in Biblical Studies."),
            Speaker(name:"Michael Whitworth", location:"Fort Worth, TX", photo:UIImage(named:"michaelwhitworth")!, description:"Michael Whitworth is the owner of Start2Finish, a web media and book publishing company. He is the author of over eight books, including the award-winning \"The Epic of God\" and \"The Derision of Heaven.\" He has over 12 years experience in full-time preaching and minister.\n\nMichael is a 2006 graduate of Freed-Hardeman with a degree in Bible and a minor in political science.\n\nHe and his wife Sara have three children: Daniel, Audrey, and Mikaela.\n\nIn his spare time, he enjoys reading, drinking coffee, watching sports, and spending time with his awesome family and furry golden retriever."),
            Speaker(name:"Rickie Hagan", location:"Red Boiling Springs, TN", photo:UIImage(named:"rickiehagan")!, description:"Colonel Rickie N. Hagan is a native of Monroe County, KY. He enlisted in the Kentucky National Guard in December, 1978 as a Private, 13B, Field artillery Crewman. He attended basic training at Fort Sill, Oklahoma where he was Platoon Leader, Honor Graduate, received the Battalion Commander`s Leadership Award and the Highest Physical Training award. From there he rose to the rank of Staff Sergeant. In 1985 he applied and was selected to attend the Kentucky Military Academy, Officer Candidate School at Fort Knox, KY., where he was a Distinguished Military Graduate and was commissioned a Second Lieutenant in 1986 as a Field Artillery Officer. He has 37 years of service, collectively with the National Guard, the Army Reserves and the United States Army.\n\nHe is also a former student of the Nashville School of Preaching and Biblical Studies."),
            Speaker(name:"Samuel Jones", location:"Jackson, TN", photo:UIImage(named:"samueljones")!, description:"FAMILY BACKGROUND: Married to the former Carolyn Diane King. We have five adult children.\n\nEDUCATIONAL BACKGROUND: I am a graduate of Tupelo High School. I received a B.S. degree in Biblical Studies from Freed-Hardeman University. I received both the M.A. and Ph.D. in Sociology (Family, Criminology and Gerontology) from Mississippi State University in Starkville, Mississippi. Also, I have completed post-doctorate courses in the area of Counseling Education with an emphasis in Marriage and Family Therapy.\n\nEXPERIENCE: I have been a pulpit minister for several churches in Mississippi and Tennessee. I served as a teaching assistant for several years in the Department of Sociology and Anthropology at Mississippi State University. I served as Director of Admissions and as an Associate Professor of Sociology and Bible at Magnolia Bible College in Kosciusko, Mississippi from 1984 to 1991. I have been blessed with the privilege to speak on several brotherhood lectureships and have conducted numerous gospel meetings, marriage enrichment seminars, family seminars, and youth workshops. I have published articles in several brotherhood and professional publications.\n\nMEMBERSHIPS AND COMMUNITY SERVICE: I have been involved in presenting professional papers at Sociological and Gerontological Association meetings. I am a member of the following Associations: Southern Sociological Association (SSA), Mid-South Sociological Association (MSSA), National Council of Family Relations (NCFR), and Tennessee Association for Gerontology/Geriatric Education (TAGGE). I served as a board member for the following organizations: Chester County School Board, Sunnybrook Children's Homes, Families First for Chester County, and as the Benin Bible Training Center in Benin West Africa.\n\nPRESENTLY: I am presently serving as the Associate Minister for the East Jackson congregation in Jackson, TN. I am a retired faculty member of Freed-Hardeman University where I was employed from 1991 to 2017."),
            Speaker(name:"Wes Hanson", location:"Scappoose, OR", photo:UIImage(named:"weshanson")!, description:"Wes Hanson was born and raised in the Northwest where his father, Carl Hanson, has worked as a teacher and preacher for the past 40 years. Wes came to a personal conviction regarding the truth of Christianity at age 16 after the historical proofs for Christ’s resurrection were presented to him by a counselor at Delano Bay Christian Camp. Since then he has fully committed his life to the ministry of the Word, working with both Adults and Teens. He and his wife Rachel, and their family of four live in Scappoose, OR where Wes has served as preaching minister for 14 years. He is involved in the ministry at Camp Yamhill and frequently speaks for youth events and ministry conferences."),
            Speaker(name:"Wissam Al-Aethawi", location:"Metro Detroit, MI", photo:UIImage(named:"wissamalaethawi")!, description: "I am Wissam, 37, an associate minister at Sunset church of Christ and a gospel preacher in Metro Detroit, MI. I was born and raised to a Sunni Muslim family in Baghdad, Iraq. I rejected Islam into atheism in the mid-1990's, found a copy of the Bible in '97, believed in '98 and it took me another 12 years before I could find someone to baptize me in May 2010.\n\nA graduate of the University of Baghdad, I worked as a civil engineer for 8 years after finishing my service as a Republican Guard. Then a Christian woman in the Amish country of Pennsylvania invited me to come to the U.S. I came in April 2011. Nine months later, I went to Sunset International Bible Institute in Lubbock, TX. I finished school and moved to Michigan by early 2014. I like reading, writing, and doing Bible studies. I teach in our church, at my house and other places on a regular basis. I dream of starting an Arab-speaking congregation of the Lord's church in Dearborn."),
        ]
        
        classes = [
            Class(title: "Registration and Displays", speaker:nil, location: "Music Center", timeStart: "8:30 AM", timeEnd: "9:00 AM", day: 0),
            Class(title: "It's Not Your Body!", speaker: speakers[3], location: "Music Center", timeStart: "9:00 AM", timeEnd: "10:00 AM", day: 0),
            Class(title: "Are They Saved or Lost?", speaker: speakers[6], location: "Music 306A", timeStart: "9:00 AM", timeEnd: "10:00 AM", day: 0),
            Class(title: "The Way We Walk", speaker: speakers[1], location: "Ingram 100", timeStart: "9:00 AM", timeEnd: "10:00 AM", day: 0),
            Class(title: "Islam Myth Buster", speaker: speakers[11], location: "Music Center", timeStart: "10:15 AM", timeEnd: "11:15 AM", day: 0),
            Class(title: "Radical Evangelism Pt. 1", speaker: speakers[4], location: "Music 306A", timeStart: "10:15 AM", timeEnd: "11:15 AM", day: 0),
            Class(title: "Better Teachers Pt. 1", speaker: speakers[7], location: "Ingram 100", timeStart: "10:15 AM", timeEnd: "11:15 AM", day: 0),
            Class(title: "Becoming a Two Mile Christian", speaker: speakers[9], location: "Music Center", timeStart: "1:30 PM", timeEnd: "2:30 PM", day: 0),
            Class(title: "PTSD Pt. 1", speaker: speakers[8], location: "Music Center", timeStart: "2:45 PM", timeEnd: "3:45 PM", day: 0),
            Class(title: "Beyond Our Boundaries", speaker: speakers[5], location: "Music 306A", timeStart: "2:45 PM", timeEnd: "3:45 PM", day: 0),
            Class(title: "Equipping Families to Manage Life's Storms Pt. 1", speaker: speakers[9], location: "Ingram 100", timeStart: "2:45 PM", timeEnd: "3:45 PM", day: 0),
            Class(title: "Uncomfortable Grace", speaker: speakers[2], location: "Music Center", timeStart: "4:00 PM", timeEnd: "5:00 PM", day: 0),
            Class(title: "The Mission of the Church", speaker: speakers[0], location: "Music 306A", timeStart: "4:00 PM", timeEnd: "5:00 PM", day: 0),
            Class(title: "The Cost of Being a Soldier", speaker: speakers[8], location: "Music Center", timeStart: "7:00 PM", timeEnd: "8:00 PM", day: 0),
            
            
            
            Class(title: "Registration and Displays", speaker:nil, location: "Music Center", timeStart: "8:30 AM", timeEnd: "9:00 AM", day: 1),
            Class(title: "Youth Challenge", speaker: speakers[10], location: "University Center", timeStart: "9:00 AM", timeEnd: "4:00 PM", day: 1),
            Class(title: "It's Not Your Money!", speaker: speakers[3], location: "Music Center", timeStart: "9:00 AM", timeEnd: "10:00 AM", day: 1),
            Class(title: "Fan or Follower?", speaker: speakers[6], location: "Music 306A", timeStart: "9:00 AM", timeEnd: "10:00 AM", day: 1),
            Class(title: "The Want We Have", speaker: speakers[1], location: "Ingram 100", timeStart: "9:00 AM", timeEnd: "10:00 AM", day: 1),
            Class(title: "The Temple: The 3rd of the Two Sacred Places", speaker: speakers[11], location: "Music Center", timeStart: "10:15 AM", timeEnd: "11:15 AM", day: 1),
            Class(title: "Radical Evangelism Pt. 2", speaker: speakers[4], location: "Music 306A", timeStart: "10:15 AM", timeEnd: "11:15 AM", day: 1),
            Class(title: "Better Teachers Pt. 2", speaker: speakers[7], location: "Ingram 100", timeStart: "10:15 AM", timeEnd: "11:15 AM", day: 1),
            Class(title: "Creating Contagious Faith", speaker: speakers[4], location: "Music Center", timeStart: "1:30 PM", timeEnd: "2:30 PM", day: 1),
            Class(title: "PTSD Pt. 2", speaker: speakers[8], location: "Music Center", timeStart: "2:45 PM", timeEnd: "3:45 PM", day: 1),
            Class(title: "Beyond Our Walls", speaker: speakers[5], location: "Music 306A", timeStart: "2:45 PM", timeEnd: "3:45 PM", day: 1),
            Class(title: "Equipping Families to Manage Life's Storms Pt. 2", speaker: speakers[9], location: "Ingram 100", timeStart: "2:45 PM", timeEnd: "3:45 PM", day: 1),
            Class(title: "Uncomfortable Mercy", speaker: speakers[2], location: "Music Center", timeStart: "4:00 PM", timeEnd: "5:00 PM", day: 1),
            Class(title: "Passing the Gospel Torch", speaker: speakers[0], location: "Music 306A", timeStart: "4:00 PM", timeEnd: "5:00 PM", day: 1),
            Class(title: "It's Not About You; It's All About God!", speaker: speakers[3], location: "Music Center", timeStart: "7:00 PM", timeEnd: "8:00 PM", day: 1),
            
            
            
            Class(title: "Registration and Displays", speaker:nil, location: "Music Center", timeStart: "8:30 AM", timeEnd: "9:00 AM", day: 2),
            Class(title: "It's Not Your Time!", speaker: speakers[3], location: "Music Center", timeStart: "9:00 AM", timeEnd: "10:00 AM", day: 2),
            Class(title: "Draw a Crowd or Make Disciples?", speaker: speakers[6], location: "Music 306A", timeStart: "9:00 AM", timeEnd: "10:00 AM", day: 2),
            Class(title: "The Wreck We Face", speaker: speakers[1], location: "Ingram 100", timeStart: "9:00 AM", timeEnd: "10:00 AM", day: 2),
            Class(title: "What I Learned (and Didn't Learn) From Muslims", speaker: speakers[11], location: "Music Center", timeStart: "10:15 AM", timeEnd: "11:15 AM", day: 2),
            Class(title: "Radical Evangelism Pt. 3", speaker: speakers[4], location: "Music 306A", timeStart: "10:15 AM", timeEnd: "11:15 AM", day: 2),
            Class(title: "Better Teachers Pt. 3", speaker: speakers[7], location: "Ingram 100", timeStart: "10:15 AM", timeEnd: "11:15 AM", day: 2),
            Class(title: "Dealing With Grief", speaker: speakers[7], location: "Music Center", timeStart: "1:30 PM", timeEnd: "2:30 PM", day: 2),
            Class(title: "PTSD Pt. 3", speaker: speakers[8], location: "Music Center", timeStart: "2:45 PM", timeEnd: "3:45 PM", day: 2),
            Class(title: "Beyond Our Words", speaker: speakers[5], location: "Music 306A", timeStart: "2:45 PM", timeEnd: "3:45 PM", day: 2),
            Class(title: "Equipping Families to Manage Life's Storms Pt. 3", speaker: speakers[9], location: "Ingram 100", timeStart: "2:45 PM", timeEnd: "3:45 PM", day: 2),
            Class(title: "As a Light to the Muslims", speaker: speakers[10], location: "Music Center", timeStart: "5:00 PM", timeEnd: "6:00 PM", day: 2),
            
        ]
    }
}
