//
//  GlobalData.swift
//  Faithbuilders
//
//  Created by Curtis Wilson on 6/14/16.
//  Copyright © 2016 Eusebeia. All rights reserved.
//

import UIKit
class GlobalData
{
    // Singleton Setup
    
    fileprivate static var info: GlobalData?
    let speakers: Array<Speaker>
    let classes: Array<Class>
    
    class func getInstance() -> GlobalData
    {
        if self.info == nil
        {
            self.info = GlobalData()
        }
        
        return self.info!
    }
    
    func findSpeakerByName(_ name: String) -> Speaker? {
        var i: Int = 0
        while (i < speakers.count) {
            if (speakers[i].name == name) {
                return speakers[i]
            }
            i += 1
        }
        return nil
    }
    
    // Class properties
    init() {
        speakers = [
            Speaker(name:"Brandon Edwards", location:"Nashville, TN", photo:UIImage(named:"brandonedwards")!, description:"Brandon Edwards holds a few different titles in different roles. He is the Missions Minister at the Nashville Church of Christ Nashville, TN, the Vice President of Story at Aggos - a brand new private, curated social media for the Churches of Christ globally, and also the Creative Director for Hidden Bridge Media. Brandon graduated from Freed-Hardeman University in 2005 with a degree in Bible with an emphasis in Missions. He is currently working on a Master of Arts in Religion at Harvard University.\n\nIn his role at Aggos, Brandon helps churches and ministries connect across the world through the innovative Aggos platform. From missionaries using the one of a kind fundraising tool (Aggos Giving) to the event and ticketing platform (Aggos Events), Brandon travels the world connecting the church.\n\nBrandon grew up on the mission field in Florence, Italy and has spent most of his life overseas. After graduating from FHU, Brandon spent two years working in China, Vietnam, Cambodia, and Thailand before marrying the love of his life Kristin (Barnes) Edwards in May 2007. Brandon and Kristin have three children - Charlotte (10 yrs) and Duncan (3 yrs), and Cecilia Carrington (6 months).\n\n/Brandon has a love for Youth Ministry and is heavily involved in youth events all over the country as a speaker and teacher. Events include Exposure Youth Camp, Horizons at FHU, Uplift at Harding, ECEC, Inspire, EU, and T3 (Dallas).\n\nIn his role of Creative Director for Hidden Bridge Media - a media based ministry that produces high-quality graphics, videos, films, and curricula for churches across the world. You can find out more about HBMedia at www.hiddenbridgemedia.org."),
            Speaker(name:"Dan Winkler", location:"Huntingdon, TN", photo:UIImage(named:"danwinkler")!, description:"Dan Winkler has been preaching the unsearchable riches of Jesus since 1969. Currently he is one of two ministers working with the Huntingdon Church of Christ in Huntingdon, TN.\n\nHe is a graduate of Oklahoma Christian University where he received a degree in Bible, minoring in Greek and Speech and he holds a Masters degree in New Testament studies from David Lipscomb University. He is currently an adjunct teacher at Freed-Hardeman University.\n\nHe is the author of several books including such titles as:\nHarmony Among the Heirs of Heaven\nChristianity is a Great Way of Life\nHebrews: God’s Word of Encouragement\nActs: The Church We Love\nRomans: Just-if-ied Never Sinned\nRevelation: The Church at Home with God\nHeaven: My Father’s House\nPrayer: When I Kneel at the Throne of God\nAngels: The Ministers of Heaven\nA 1 Corinthians 13 Christian\nSome of Jesus' Favorite Stories – the Parables\n\nHe and his wife Diane have been blessed with three great sons and seven beautiful grandchildren."),
            Speaker(name:"Dennis Baker", location:"Tacoma, WA", photo:UIImage(named:"dennisbaker")!, description:"Dennis Baker is the minister for Lakeview Church of Christ in Tacoma, Washington where he has served the body for over 20 years. He is the director of STS at Delano Bay Christian Camp. He graduated from the Preston Road School of Preaching in Dallas, Texas. He and his wife, Lanita, have been married for over 30 years and have three children."),
            Speaker(name:"Don Jacobs", location:"Olympia, WA", photo:UIImage(named:"donjacobs")!, description:"Don Jacobs has been in full time or part time ministry in churches of Christ for over 32 years. He attended Harding University from 1986 to 1991 and has a BA in Biblical Counseling from American International University and a BA in Behavioral Counseling from Regent University. Don has worked full time as a Counselor/Social Worker for foster children and their families for over 24 years. Don is married to Cindy Jacobs who is a Special Education teacher. They have three adult children, Kendra, Sarah and Tyler, and two son-in-laws, all of which are active members in the Lord's church, and his pride and joy, four grandchildren with another on the way."),
            Speaker(name:"John DeBerry", location:"Memphis, TN", photo:UIImage(named:"johndeberry")!, description: "Tennessee State Representative\n\n1207 Sledge Street, Memphis, TN 38104\n\nRepresenting House District 90 since 1995. Representative Deberry has been a House member of the 99th through 110th General Assemblies. He is currently serving on the House Education Administration and Planning Committee, House Education Administration and Planning Subcommittee and Finance Ways and Means Committee. Rep. Deberry was also elected by the Democrat Caucus as Minority Leader Pro Tempore.\n\nRepresentative Deberry is a member of the National Conference of State Legislators (NCSL) Education Committee and Co-Chair of the Council of State Governments (CSG) Education Committee. Representative Deberry also serves on the Governor's Task force for Sentencing and Recidivism. Representative Deberry has been appointed by Speaker Harwell to serve on the Second Look Commission and also serves on the Three Branches Institute and is a board member of SCORE (State Collaborative on Reforming Education).\n\nRepresentative Deberry is former Chairman of the Tennessee Black Caucus of State Legislators and Former Chairman of the Children and Family Affairs Committee\n\nRepresentative Deberry's community involvement includes membership with the following organizations: NAACP; Boy Scouts of America; Operation Weed & Seed, Junior Achievement; YFU International Youth Exchange, Bethany Homes (Counselor), Chairman, DMC Task Force, TN Commission on Children and Youth, Board of Trustees, Freed-Hardeman University, Memphis & Shelby County Juvenile Court Advisory Council, Tennessee Arts Caucus and Former Chairman of Tennessee Alcohol Commission\n\nPresident of John J. Deberry and Associates, he has over twenty-five years of experience as a marketing, advertising and public relations executive."),
            Speaker(name:"Julian Webster", location:"Nashville, TN", photo:UIImage(named:"julianwebster")!, description:"He is a member of the 15th Ave. Church of Christ where he serves as a teacher, and a benevolence leader. He has been preaching the lord’s word for 11 years and has been the Youth minister at 15th Ave. for 7 of those years. He graduated from Howard University with distinction earning a bachelor’s of Science in Health Management. While in college he competed for 3 years in the American Forensics’ Association for Public speaking winning numerous awards for his speaking abilities. In 2017 he graduated from the Nashville School of Preaching on the Preachers track. He’s spoken at many Youth days, and taught classes at the Tennessee State Youth Conference. Baptized at the age of 9 Bro. Webster has been a member of the lord’s church for over 24 years and intends on doing God's will for many years to come."),
            Speaker(name:"Kenney Johnson", location:"Seattle, WA", photo:UIImage(named:"kenneyjohnson")!, description:"Brother Kenney has been preaching for the Churches of Christ for over 20 years. Ken started as an Associate Minister in Portland and has served congregations in both California and Washington. Kenney is currently the Minister of the Southside Church in Seattle, WA. Kenney holds a Bachelor of Arts degree in Communications and Leadership from Southern Christian. Secularly Kenney has developed and managed corporate facilities for large real and asset companies.\n\nKenney is married to Rene Johnson, whose union was orchestrated by the power of God's love. They met over 20 years ago on a blind date while he was a sophomore at Edmond's College in Seattle Washington. It was also during this period of time Bro Johnson's late father Lonnie Johnson taught Rene about Jesus Christ, who initially had no previous religious knowledge or upbringing in the Gospel, and was baptized into Christ in 1989. Kenney and Rene are the parents of four beautiful gifts from God: Derrick, Marcellus, Keanna and Darius, and proud grandparents of four grand children."),
            Speaker(name:"Lee Jamieson", location:"Tallahassee, FL", photo:UIImage(named:"leejamieson")!, description:"Lee R. Jamieson has served as the Pulpit Minister for the Timberlane Church of Christ in Tallahassee, Florida since February 2014. Previously, he served in the same capacity for congregations in Tuscaloosa, Alabama and Luverne, Alabama. In all, Lee has been in full-time ministry since 2001. He earned his undergraduate degree from the University of North Carolina in 1986 and a Masters Degree from Southern Christian University in Montgomery, Alabama in 2002.\n\nMarried to Kathy for 29 years, the couple has a son, Lee, Jr., who is a sophomore studying at the University of Alabama and a daughter, Madelaine (“Maddy”), who is a freshman at Tallahassee Community College in Tallahassee. Both Lee, Jr. and Maddy are engaged to be married in the summer of 2017.\n\nTogether with his family, Lee has led annual trips to the Republic of Panama working with the indigenous Embera and Kuna tribesmen and other rural Panamanian people in a combined humanitarian and evangelistic outreach. Lee and his family are also actively engaged in summer youth camps and various youth retreats throughout the southeast.\n\nFavorite Bible verse …\nThus says the LORD: \"Let not the wise man boast in his wisdom, let not the mighty man boast in his might, let not the rich man boast in his riches, but let him who boasts boast in this, that he understands and knows me, that I am the LORD who practices steadfast love, justice, and righteousness in the earth. For in these things I delight, declares the LORD.\"\nJeremiah 9:23-24"),
            Speaker(name:"Mike Greene", location:"Nashville, TN", photo:UIImage(named:"michaelgreene")!, description:"Michael served as a full-time preacher for 45 years, serving churches in Tennessee, Georgia and Kentucky. The last nine years he served the Lehman Avenue congregation in Bowling Green, Kentucky. Michael has preached the gospel in more than a dozen states and done mission work in nine different foreign countries. He has also been very active in summer youth camp work.\n\nHe and his wife Mary retired at the end of 2016 and moved back to Columbia, Tennessee, to spend more time with their son, Joey, daughter-in-law Amy, and their two grandchildren, Samantha and Anzly.\n\nMichael now serves as Director of the Nashville School of Preaching and speaks at Summer Series programs, Vacation Bible Schools, gospel meetings and fill in appointments."),
            Speaker(name:"Ronnie Morrison", location:"Tacoma, WA", photo:UIImage(named:"ronniemorrison")!, description:"For more than 48 years, Ronnie Morrison has served in ministry, preaching for churches in the states of Washington, Texas, Oklahoma, and Arkansas.\n\nFor the past 24 years, Ronnie and his wife of 50 years, Rowena, have served as missionaries in Russia and Ukraine. They recruited, trained, and led hundreds of Christian soldiers on evangelistic campaigns. Fifty churches were established and 5,000 Slavics were saved by the blood of Jesus Christ.\n\nRonnie also taught biblical courses at Southern Christian University and at Ukrainian Bible Institute. He holds both a bachelor or art in theology degree and a master of science from Ambridge University. He also has a Certificate of Graduation in evangelistic training and advanced biblical studies from Preston Road School of Preaching.\n\nIn the late 1970's and early 80's, Ronnie and Rowena served as missionaries in New Zealand. For several years, Ronnie has also worked in the business world of financial services as a Regional Vice-President with Primerica.\n\nRonnie has also written Open Doors & Receptive Hearts, a book about his mission work in the Slavic nations and among the Slavic people. Ronnie also wrote Kids on the Block, a book about his 10 years growing up in a rough neighborhood. Both books are available on Amazon.\n\nRonnie and Rowena currently live in Tacoma, WA and have three married children- a daughter and two sons- and enjoy their nine grandchildren and three great-grandchildren."),
            Speaker(name:"Sheila Butt", location:"Columbia, TN", photo:UIImage(named:"sheilabutt")!, description: "Sheila Butt was born in Rockford, IL, and attended East Tennessee State University. She graduated with a B.S. in English with a minor in History. She has also studied Greek and Hermeneutics at David Lipscomb University. She is married to Stan Butt Sr., a minister and the Executive Director for the Tennessee Dairy Association. She and Stan have three sons and nine grandchildren.\n\nSheila graduated from the Women's Program at Bear Valley Bible Institute and has taught Ladies' Days, Teens Girls' Days and in Lectureships for the past 25 years. She has been on numerous mission trips to many of the Caribbean Islands, Honduras, Panama and Alaska. She taught in the Horizons Program at Freed-Hardeman University for almost 20 years and received the Kay Battles Service Award from that program. Sheila has written two books for ladies and teen girls and co-authored another with several women entitled, We Bow Down. Sheila was the recipient of the Publishing Designs \"Golden Pen Award\" for her work on those publications. She has written articles for Christian Woman Magazine and was featured in Christian Woman for her service as a Tennessee State Legislator.\n\nSheila Butt was elected to the Tennessee General Assembly in 2010, serving the 64th District and has served in four General Assemblies. She has served on the Agriculture Committee, The Criminal Justice Committee, The Education Committee and the Health Committee. She has also served as the House Majority Floor Leader.\n\nSheila was the 2016 recipient of the Agriculture Legislator of the Year Award by the Tennessee Cattlemen's Association. She has also received the \"Iron Lady Award\" from the 9.12 Nashville Project in 2015. In November of 2013, Sheila received the \"Elected Women of Excellence Award\" by the National Foundation for Women Legislators. Sheila is known nationwide for her integrity and for her articulate message of standing for \"Faith, Family and Freedom.\""),
            Speaker(name:"Thomas Morse", location:"Renton, WA", photo:UIImage(named:"thomasmorse")!, description: "Thomas Morse earned his bachelor's from the United States Naval Academy in 2009. He grew up at the Covington-Sawyer church of Christ, and returned to the PNW after a little over six years of service in the Marines as a Tank Officer. Since his return he has been running the kids and youth programs for Springbrook church of Christ. He led the effort at Springbrook to renew and repurpose a program called, Lamplighters. This program is now an at home devotional program where people are brought into God's story through reading, singing and praying together."),
        ]
        
        classes = [
            Class(title: "Registration and Displays", speaker:nil, location: "Foyer", timeStart: "8:30 AM", timeEnd: "9:00 AM", day: 0),
            Class(title: "By the Blood of the Cross", speaker: speakers[7], location: "Auditorium", timeStart: "9:00 AM", timeEnd: "10:00 AM", day: 0),
            Class(title: "The Fear of the Lord", speaker: speakers[9], location: "Room #1", timeStart: "9:00 AM", timeEnd: "10:00 AM", day: 0),
            Class(title: "Fostering Reconciliation", speaker: speakers[3], location: "Room #2", timeStart: "9:00 AM", timeEnd: "10:00 AM", day: 0),
            Class(title: "Forgiving Myself", speaker: speakers[1], location: "Auditorium", timeStart: "10:15 AM", timeEnd: "11:15 AM", day: 0),
            Class(title: "What is Family Ministry?", speaker: speakers[2], location: "Room #1", timeStart: "10:15 AM", timeEnd: "11:15 AM", day: 0),
            Class(title: "Fellowship Conundrum", speaker: speakers[6], location: "Room #2", timeStart: "10:15 AM", timeEnd: "11:15 AM", day: 0),
            Class(title: "The Relationship of 2 Corinthians to 1 Corinthians", speaker: speakers[8], location: "Auditorium", timeStart: "1:30 PM", timeEnd: "2:30 PM", day: 0),
            Class(title: "Brother to Brother", speaker: speakers[8], location: "Auditorium", timeStart: "2:45 PM", timeEnd: "3:45 PM", day: 0),
            Class(title: "The Beauty of Reconciliation", speaker: speakers[10], location: "Room #1", timeStart: "2:45 PM", timeEnd: "3:45 PM", day: 0),
            Class(title: "Joseph and his Brothers", speaker: speakers[5], location: "Room #2", timeStart: "2:45 PM", timeEnd: "3:45 PM", day: 0),
            Class(title: "World Through Eyes of Faith (Part 1)", speaker: speakers[4], location: "Auditorium", timeStart: "4:00 PM", timeEnd: "5:00 PM", day: 0),
            Class(title: "A Christian Online Community", speaker: speakers[0], location: "Room #1", timeStart: "4:00 PM", timeEnd: "5:00 PM", day: 0),
            Class(title: "Reconciliation in the Home - Lamplighters (Part 1)", speaker: speakers[11], location: "Room #2", timeStart: "4:00 PM", timeEnd: "5:00 PM", day: 0),
            Class(title: "Reconciled in Glory", speaker: speakers[7], location: "Auditorium", timeStart: "7:30 PM", timeEnd: "8:30 PM", day: 0),
            
            
            
            Class(title: "Registration and Displays", speaker:nil, location: "Foyer", timeStart: "8:30 AM", timeEnd: "9:00 AM", day: 1),
            Class(title: "For the Glory of God", speaker: speakers[7], location: "Auditorium", timeStart: "9:00 AM", timeEnd: "10:00 AM", day: 1),
            Class(title: "The Love of Christ", speaker: speakers[9], location: "Room #1", timeStart: "9:00 AM", timeEnd: "10:00 AM", day: 1),
            Class(title: "Adoption Reconciliation", speaker: speakers[3], location: "Room #2", timeStart: "9:00 AM", timeEnd: "10:00 AM", day: 1),
            Class(title: "Forgiving Others", speaker: speakers[1], location: "Auditorium", timeStart: "10:15 AM", timeEnd: "11:15 AM", day: 1),
            Class(title: "The Goal of Family Ministry", speaker: speakers[2], location: "Room #1", timeStart: "10:15 AM", timeEnd: "11:15 AM", day: 1),
            Class(title: "Race Reconciliation (Part 1)", speaker: speakers[6], location: "Room #2", timeStart: "10:15 AM", timeEnd: "11:15 AM", day: 1),
            Class(title: "Connecting People to God", speaker: speakers[5], location: "Auditorium", timeStart: "1:30 PM", timeEnd: "2:30 PM", day: 1),
            Class(title: "Leadership to Members", speaker: speakers[8], location: "Auditorium", timeStart: "2:45 PM", timeEnd: "3:45 PM", day: 1),
            Class(title: "Jesus and Reconciliation", speaker: speakers[10], location: "Room #1", timeStart: "2:45 PM", timeEnd: "3:45 PM", day: 1),
            Class(title: "David and the Lord", speaker: speakers[5], location: "Room #2", timeStart: "2:45 PM", timeEnd: "3:45 PM", day: 1),
            Class(title: "World Through Eyes of Faith (Part 2)", speaker: speakers[4], location: "Auditorium", timeStart: "4:00 PM", timeEnd: "5:00 PM", day: 1),
            Class(title: "Evangelizing through Social Media", speaker: speakers[0], location: "Room #1", timeStart: "4:00 PM", timeEnd: "5:00 PM", day: 1),
            Class(title: "Reconciliation in the Home - Lamplighters (Part 2)", speaker: speakers[11], location: "Room #2", timeStart: "4:00 PM", timeEnd: "5:00 PM", day: 1),
            Class(title: "Need to Reconcile", speaker: speakers[4], location: "Auditorium", timeStart: "7:30 PM", timeEnd: "8:30 PM", day: 1),
            
            
            
            Class(title: "Registration and Displays", speaker:nil, location: "Foyer", timeStart: "8:30 AM", timeEnd: "9:00 AM", day: 2),
            Class(title: "For the World to See", speaker: speakers[7], location: "Auditorium", timeStart: "9:00 AM", timeEnd: "10:00 AM", day: 2),
            Class(title: "The Commission of Christ", speaker: speakers[9], location: "Room #1", timeStart: "9:00 AM", timeEnd: "10:00 AM", day: 2),
            Class(title: "Return Home Reconciliation", speaker: speakers[3], location: "Room #2", timeStart: "9:00 AM", timeEnd: "10:00 AM", day: 2),
            Class(title: "Forgiving God", speaker: speakers[1], location: "Auditorium", timeStart: "10:15 AM", timeEnd: "11:15 AM", day: 2),
            Class(title: "Effective Family Ministry", speaker: speakers[2], location: "Room #1", timeStart: "10:15 AM", timeEnd: "11:15 AM", day: 2),
            Class(title: "Race Reconciliation (Part 2)", speaker: speakers[6], location: "Room #2", timeStart: "10:15 AM", timeEnd: "11:15 AM", day: 2),
            Class(title: "Racial Reconciliation", speaker: speakers[5], location: "Auditorium", timeStart: "1:30 PM", timeEnd: "2:30 PM", day: 2),
            Class(title: "Members to Leadership", speaker: speakers[8], location: "Auditorium", timeStart: "2:45 PM", timeEnd: "3:45 PM", day: 2),
            Class(title: "Hannah", speaker: speakers[10], location: "Room #1", timeStart: "2:45 PM", timeEnd: "3:45 PM", day: 2),
            Class(title: "Saul and Jesus", speaker: speakers[5], location: "Room #2", timeStart: "2:45 PM", timeEnd: "3:45 PM", day: 2),
            Class(title: "World Through Eyes of Faith (Part 3)", speaker: speakers[4], location: "Auditorium", timeStart: "4:00 PM", timeEnd: "5:00 PM", day: 2),
            Class(title: "The Art of Creative Ministry", speaker: speakers[0], location: "Room #1", timeStart: "4:00 PM", timeEnd: "5:00 PM", day: 2),
            Class(title: "Grace: Reconciled to God", speaker: speakers[1], location: "Auditorium", timeStart: "5:30 PM", timeEnd: "6:30 PM", day: 2),
            
        ]
    }
}
